### ISSUE TITLE
Unable to locate `cargo-sweep`

### ISSUE THREAD

**Issue by BD103** [BD103/cargo-sweep#8]
https://github.com/Leafwing-Studios/cargo-cache/issues/36

People have been having issues where `cargo-sweep` cannot be found. I'm considering removing `cargo-sweep` installation and switching to a hand-rolled Javascript version.

```
Restoring `cargo-sweep` from cache.
Building `cargo-sweep` from scratch. # builds and installs fine
Creating timestamp.
/__w/_actions/BD103/cargo-sweep/v1/dist/main/index.js:10004
                    throw new Error(`Unable to locate executable file: ${tool}. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`);
                          ^

Error: Unable to locate executable file: /github/home/.cargo/bin/cargo-sweep. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
    at Object.<anonymous> (/__w/_actions/BD103/cargo-sweep/v1/dist/main/index.js:10004:27)
    at Generator.next (<anonymous>)
    at fulfilled (/__w/_actions/BD103/cargo-sweep/v1/dist/main/index.js:9857:58)
```

**Comment by BD103** [comment]
Fixed with [`v2.0.0`](https://github.com/BD103/cargo-sweep/releases/tag/v2.0.0).
